levels:
  md:
    discovery:
      markdown:
        flags: ""
      rst:
        flags: ""
    tool:
      markdownlint:
        flags: ""
      rstcheck:
        flags: ""
      rstlint:
        flags: ""

  md_with_pylint:
    inherits_from: "md"
    discovery:
      python:
        flags: ""
    tool:
      pylint:
        flags: "--good-names=f,i,j,k,x,y,z,ex,_"
